name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Install Dependencies
      run: yarn
    - name: Build & Deploy
      run: yarn deploy
      env:
        FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
